version: 2
updates:
    - package-ecosystem: cargo
      directory: /backend/
      schedule:
          interval: daily
      open-pull-requests-limit: 100

    # Actions
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
