name: Lint Codes

# This workflow run tests and build for each push

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Update local toolchain
              run: |
                  rustup update
                  rustup install nightly
                  rustup component add clippy

            - name: Toolchain info
              run: |
                  cargo --version --verbose
                  rustc --version
                  cargo clippy --version

            - name: Lint
              run: |
                  cargo fmt -- --check
                  cargo clippy -- -D warnings
