name: Unit Test

# This workflow run tests and build for each push

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    unit_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Update local toolchain
              run: |
                  rustup update
                  rustup install nightly

            - name: Toolchain info
              run: |
                  cargo --version --verbose
                  rustc --version

            - name: Test
              run: |
                  cargo check
                  cargo test --all
